### ISSUE TITLE
ttf-emojione 4.5 is attached

### ISSUE THREAD

**Issue by maximbaz** [joypixels/emojione-assets#40]
Seems Travis is [still](https://travis-ci.org/emojione/emojione-assets/jobs/483634011) [broken](https://github.com/travis-ci/dpl/issues/816) 😞 

Anyways, I'm attaching `.ttf` files for the latest release, please add those to the release on Github 😉 

I'm not sure if you decided to [abandon `-alt` variant or not](https://github.com/emojione/emojione-assets/issues/38), it is attached just in case as well.

~~The archive is too big for Github, download from here: link~~
New location: [link](https://github.com/maximbaz/emojione-fonts/releases)

/cc @caseyahenson

**Comment by caseyahenson** [comment]
@maximbaz amazing, thank you! These are looking great. 🥇

**Comment by Schnob** [comment]
Hi! Is it possible to have a `.ttc` file as well? Thank you

**Comment by maximbaz** [comment]
This has been generated via [maximbaz/docker-emojione-fonts-build](https://github.com/maximbaz/docker-emojione-fonts-build) which is only able to build `.ttf` files, if you or anyone else knows how to create `.ttc` format, PRs are very welcome 🙂

**Comment by maximbaz** [comment]
@caseyahenson could you please attach these files to the [Github release page](https://github.com/emojione/emojione-assets/releases/tag/4.5)?

**Comment by maximbaz** [comment]
Obsolete, closing
